global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'secure-api-storage'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API metrics
  - job_name: 'backend-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['secure-key-storage:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'backend-api'

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # PostgreSQL exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Nginx exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  # Custom application metrics
  - job_name: 'app-metrics'
    static_configs:
      - targets: ['secure-key-storage:8000']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'app_.*'
        action: keep